# Generated by Django 3.2 on 2021-04-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
            ],
        ),
    ]
