# Generated by Django 3.2 on 2021-04-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagenes',
            field=models.ImageField(default='foto_perfil.png', upload_to=''),
        ),
    ]
