# Generated by Django 3.2 on 2021-04-08 23:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_relacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relacion',
            new_name='Relationship',
        ),
    ]
